InseeFr/Pogues-Back-Office

- src/main/java/fr/insee/pogues/persistence/service/QuestionnairesService.java
- src/main/java/fr/insee/pogues/persistence/service/QuestionnairesServiceImpl.java
- src/main/java/fr/insee/pogues/user/model/User.java
- src/main/java/fr/insee/pogues/user/query/UserServiceQuery.java
- src/main/java/fr/insee/pogues/user/query/UserServiceQueryLDAPImpl.java
- src/main/java/fr/insee/pogues/user/service/UserService.java
- src/main/java/fr/insee/pogues/user/service/UserServiceImpl.java
- src/main/java/fr/insee/pogues/webservice/rest/OwnerSpecific.java
- src/main/java/fr/insee/pogues/webservice/rest/OwnerSpecificFilter.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesException.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesUser.java
- src/main/resources/pogues-bo.properties
> Refactoring fix #5

- src/main/java/fr/insee/pogues/persistence/service/QuestionnairesServiceImpl.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesPersistence.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesUser.java
- src/test/java/fr/insee/pogues/rest/test/TestPoguesPersistence.java
- src/test/java/fr/insee/pogues/rest/test/TestPoguesUser.java
Resolve user group client side rather than server side is more consistent in our case.
> Fix get by owner

- src/main/java/fr/insee/pogues/webservice/rest/PoguesTransforms.java
- src/main/resources/env/dev/pogues-bo.properties
- src/main/resources/env/dv/pogues-bo.properties
- src/main/resources/env/prod/pogues-bo.properties
- src/main/resources/env/qa/pogues-bo.properties
- src/main/resources/env/qf/pogues-bo.properties
- Fix trailing slash in visualization URL 7c738c5bd2948ce337899e5e9786eff720502a28
- Stick to model: rename survey to DataCollection ad2dfd0b6d7cfa444746ab8e166276d4286f186e
> Bug fixes in visualization process

- src/main/java/fr/insee/pogues/webservice/rest/PoguesTransforms.java
95a909176c48b32b6469dcd167460add7fadb1f5
> Fix: property case

- .travis.yml
- pom.xml
- scripts/install.sh
- src/main/java/fr/insee/pogues/config/ApplicationContext.java
- src/main/java/fr/insee/pogues/persistence/query/QuestionnairesServiceQuery.java
- src/main/java/fr/insee/pogues/persistence/query/QuestionnairesServiceQueryPostgresqlImpl.java
- src/main/java/fr/insee/pogues/persistence/service/QuestionnairesService.java
- src/main/java/fr/insee/pogues/persistence/service/QuestionnairesServiceImpl.java
- src/main/java/fr/insee/pogues/webservice/rest/OwnerRestrictedFilter.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesPersistence.java
- src/test/java/fr/insee/pogues/persistence/TestQuestionnaireService.java
- src/test/java/fr/insee/pogues/rest/TestPoguesPersistence.java
- Allow properties override from file system
- Temporary rollback e2e tests due to releases deployment issues
> Improve properties and environment management

- src/main/java/fr/insee/pogues/metadata/client/MetadataClientImpl.java
commit 9d4775dbf3e2621d09414e580d6765f63d60d289
273A-BO Add new Units (ex: heures, jours, mois, années)
> 273A-BO Add new Units (ex: heures, jours, mois, années)

- .travis.yml
- pom.xml
- src/main/java/fr/insee/pogues/api/remote/eno/transforms/EnoClient.java
- src/main/java/fr/insee/pogues/api/remote/eno/transforms/EnoClientImpl.java
- src/main/java/fr/insee/pogues/transforms/XpathToVtl.java
- src/main/java/fr/insee/pogues/transforms/XpathToVtlImpl.java
- src/main/java/fr/insee/pogues/utils/json/JSONFunctions.java
- src/main/java/fr/insee/pogues/utils/vtl/Analyser.java
- src/main/java/fr/insee/pogues/utils/vtl/AnalyserResult.java
- src/main/java/fr/insee/pogues/utils/vtl/BindingsUtils.java
- src/main/java/fr/insee/pogues/utils/vtl/Variable.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesTransforms.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesUtils.java
- src/test/java/fr/insee/pogues/utils/json/TestJSONFunctions.java
- src/test/java/fr/insee/pogues/utils/vtl/TestAnalyser.java
- src/test/resources/vtl/questionnaire-simpsons.json
WARNING : compilation with jdk 11 only (because of vtl-engine)
> Dev check formula : syntax analyzer

- pom.xml
- src/main/resources/application.properties
Limit the pool size of connections to the database
> Dev pool size

- src/main/java/fr/insee/pogues/exception/IllegalFlowControlException.java
- src/main/java/fr/insee/pogues/transforms/visualize/PoguesJSONToPoguesJSONDerefImpl.java
- src/test/java/fr/insee/pogues/transforms/TestPipeline.java
- src/test/java/fr/insee/pogues/transforms/visualize/PoguesJSONToPoguesJSONDerefImplTest.java
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/l4i3m6qa.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/l6dnlrka.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/lct78jr8.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/lct8pcsy.json
Cherry-picked commits from `dev-compo-visu-fat-jat` to `dev-compo-visu`
> Dev compo visu validated

- .gitignore
- pogues.properties
- pom.xml
- src/main/java/fr/insee/pogues/api/remote/eno/transforms/EnoClientImpl.java
- src/main/java/fr/insee/pogues/config/auth/security/restrictions/StampsRestrictionsService.java
- src/main/java/fr/insee/pogues/config/auth/security/restrictions/StampsRestrictionsServiceImpl.java
- src/main/java/fr/insee/pogues/persistence/query/QuestionnairesServiceQueryPostgresqlImpl.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesException.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesPersistence.java
- src/main/java/fr/insee/pogues/webservice/rest/PoguesTransforms.java
- src/main/resources/application.properties
Branch 'dev-stromae-v2-lunatic-v2' contains updates for Stromae v2 & Lunatic v2 features, including "paiwise links" feature.
---
Resolved 1 minor conflict in `src/main/java/fr/insee/pogues/webservice/rest/PoguesTransforms.java`:
```
params.put("mode", "CAPI"); // from dev-stromae-v2-lunatic-v2
params.put("needDeref", ref); // from dev-compo-visu
// => kept both
```
Tests are passing but I didn't reviewed changes in details.
> Merged 'dev-stromae-v2-lunatic-v2'

- src/main/java/fr/insee/pogues/utils/PoguesModelUtils.java
- src/test/java/fr/insee/pogues/transforms/visualize/PoguesJSONToPoguesJSONDerefImplTest.java
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/acceptance_test_1/l4i3m6qa_referenced.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/acceptance_test_1/lfqic931_reference.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/acceptance_test_2/l4i3m6qa_referenced.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/acceptance_test_2/lfqw6sdu_referenced.json
- src/test/resources/transforms/PoguesJSONToPoguesJSONDeref/acceptance_test_2/lfqx2030_reference.json
> Fix: member reference property in iteration objects

- pom.xml
- src/main/java/fr/insee/pogues/persistence/query/QuestionnairesServiceQueryPostgresqlImpl.java
* feat: add entries in persistence/questionnaires/search/meta
* chore: bump version to 4.2.1
> Feat/update metadata endpoint (#166)

- pom.xml
- src/main/java/fr/insee/pogues/persistence/query/QuestionnairesServiceQueryPostgresqlImpl.java
> fix: 'Name' property can be null in legacy questionnaires

- .github/workflows/ci.yaml
- .github/workflows/tag-release.yaml
- .github/workflows/test.yaml
- Dockerfile
- pom.xml
- java 11 to 17 in pom
- update java github actions in workflows
- use java 17 image in Dockerfile
> build: java 17

- pom.xml
Include fixes for missing properties 'url', 'version' and 'meloto'.
> fix(suggester): update pogues-model

- .github/workflows/create-release.yaml
- pom.xml
dependabot / renovate PRs
To do: disable dependabot and review renovate config
> build: update dependencies

- pom.xml
Include a new property for dynamic table controls.
> feat(pogues model): dynamic table line controls

- src/main/java/fr/insee/pogues/api/remote/eno/transforms/EnoClientImpl.java
- src/main/java/fr/insee/pogues/webservice/rest/VisualizeWithURI.java
Restore https://github.com/InseeFr/Pogues-Back-Office/pull/265
> Feat/visualize question component (DSFR)

- pom.xml
When this branch is ready to be merged in main:
> Next: 4.7.5

- .github/workflows/create-release.yaml
- .github/workflows/create-snapshot.yaml
- .github/workflows/test.yaml
- pom.xml
Update Pogues-Model version with dynamic unit properties
> feat: dynamic unit

- pom.xml
- src/main/java/fr/insee/pogues/webservice/rest/QuestionnaireController.java
- src/test/java/fr/insee/pogues/controllers/QuestionnaireControllerTest.java
> fix: 400 error at creation and add test

- src/main/java/fr/insee/pogues/service/ModelCleaningService.java
- src/main/java/fr/insee/pogues/utils/model/cleaner/ControlCriticityCleaner.java
- src/main/java/fr/insee/pogues/utils/model/cleaner/ModelCleaner.java
- src/main/java/fr/insee/pogues/utils/model/cleaner/TableDimensionCleaner.java
- src/test/java/fr/insee/pogues/service/ModelCleaningServiceTest.java
Split model cleaning logic for easy maintenance
> ref: split modelCleaning logic

- pom.xml
- src/main/java/fr/insee/pogues/utils/model/cleaner/TableDimensionCleaner.java
- src/main/java/fr/insee/pogues/utils/model/question/Table.java
- src/test/java/fr/insee/pogues/service/ModelCleaningServiceTest.java
- mi,/max VTL (handle old modeling)
- zip metadata (with ref)
- codeList & nomeclatures end-point for versions
⚠️ we have to deploy synchronously with EnoV2 (poguesxml->DDI) & EnoV3 (pogues+ddi -> Lunatic)
**ToDo**: use CRON job to clean all questionnaire in database (and not only on GET )
> feat: min max vtl dynamic table

- pom.xml
- src/main/java/fr/insee/pogues/persistence/service/QuestionnairesServiceImpl.java
- src/main/java/fr/insee/pogues/service/ModelCleaningService.java
- src/main/java/fr/insee/pogues/transforms/visualize/PoguesJSONToPoguesJSONDerefImpl.java
- src/main/java/fr/insee/pogues/utils/model/cleaner/LoopMinMaxCleaner.java
- src/main/java/fr/insee/pogues/webservice/rest/ModelTransform.java
- src/main/java/fr/insee/pogues/webservice/rest/QuestionnaireController.java
- src/main/java/fr/insee/pogues/webservice/rest/VisualizeWithURI.java
- src/test/java/fr/insee/pogues/controllers/QuestionnaireControllerTest.java
- src/test/java/fr/insee/pogues/persistence/TestQuestionnaireService.java
- src/test/java/fr/insee/pogues/service/ModelCleaningServiceTest.java
- src/test/java/fr/insee/pogues/service/stub/StubQuestionnaireService.java
- src/test/java/fr/insee/pogues/transforms/TestPipeline.java
- src/test/java/fr/insee/pogues/transforms/visualize/PoguesJSONToPoguesJSONDerefImplTest.java
- src/test/java/fr/insee/pogues/utils/model/cleaner/LoopMinMaxCleanerTest.java
La prop `"shouldSplitIterations"` ajoutée dans les boucles pour la fonctionnalité de boucle paginées par occurrences
> feat: loops paginated by occurrence
